name: Build & Push backend
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        
env:
  ACR_NAME: glqaacrdnclcacntest.azurecr.io
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build-and-push-builder:
    name: Build and Push devlake builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - name: Build and push lake image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          target: builder
          tags: ${{ env.ACR_NAME }}/devlake:amd64-builder
          platforms: linux/amd64
          builder: docker
          cache-from: ${{ env.ACR_NAME }}/devlake:amd64-builder
          cache-to: ${{ env.ACR_NAME }}/devlake:amd64-builder
  build-and-push-base:
    name: Build and Push devlake base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - name: Build and push lake image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          target: base
          tags: ${{ env.ACR_NAME }}/devlake:base
          platforms: linux/amd64,linux/arm64
          builder: docker
          cache-from: ${{ env.ACR_NAME }}/devlake:base
          cache-to: ${{ env.ACR_NAME }}/devlake:base
  build-devlake:
    needs: build-and-push-builder
    name: Build and cache devlake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["arm64", "amd64"]
    steps:
      - uses: actions/checkout@v3
      - name: Get short sha
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - uses: actions/cache@v3
        with:
          path: /tmp/devlake-build-cache-${{ matrix.platform }}
          key: buildx-devlake-build-cache-${{ github.run_id }}-${{ matrix.platform }}
      - name: Build and cache lake build
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: false
          target: build
          tags: ${{ env.ACR_NAME }}/devlake:build-cache-${{ matrix.platform }}
          platforms: linux/${{ matrix.platform }}
          builder: docker
          cache-from: ${{ env.ACR_NAME }}/devlake:amd64-builder
          cache-to: type=local,mode=min,dest=/tmp/devlake-build-cache-${{ matrix.platform }}
          build-args: |
            TAG=${{ github.ref_name }}
            SHA=${{ steps.get_short_sha.outputs.SHORT_SHA }}
  build-and-push-devlake:
    needs: [build-devlake, build-and-push-base]
    name: Build and Push devlake image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get short sha
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - uses: actions/cache@v3
        with:
          path: /tmp/devlake-build-cache-amd64
          key: buildx-devlake-build-cache-${{ github.run_id }}-amd64
      - uses: actions/cache@v3
        with:
          path: /tmp/devlake-build-cache-arm64
          key: buildx-devlake-build-cache-${{ github.run_id }}-arm64
      - name: Get push tags
        id: get_push_tags
        run: |
          image_name=${{ env.ACR_NAME }}/devlake
          if printf ${{ github.ref_name }} | grep -Pq '^v(\d+).(\d+).(\d+)$'; then
              echo "TAGS=${image_name}:latest,${image_name}:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
              echo "TAGS=${image_name}:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      - name: Build and push lake image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ steps.get_push_tags.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          builder: docker
          cache-from: |
            ${{ env.ACR_NAME }}/devlake:amd64-builder
            ${{ env.ACR_NAME }}/devlake:base
            type=local,src=/tmp/devlake-build-cache-amd64
            type=local,src=/tmp/devlake-build-cache-arm64
          build-args: |
            TAG=${{ github.ref_name }}
            SHA=${{ steps.get_short_sha.outputs.SHORT_SHA }}
      - name: Clear cache
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            for (const arch of ['amd64', 'arm64']) {
              try {
                await github.rest.actions.deleteActionsCacheByKey({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  key: `buildx-devlake-build-cache-${context.runId}-${arch}`,
                })
                console.log(`Clear cache buildx-devlake-build-cache-${context.runId}-${arch}`)
              } catch (e) {
                console.warn(`Error clear cache buildx-devlake-build-cache-${context.runId}-${arch}: ${e}`)
              }
            }
