name: Deploy Application
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: rename env
        run: mv env.example .env
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: glqaacrdnclcacntest.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}        
      - name: Deploy Application
        run: |
          sudo docker-compose up -d
